### ISSUE TITLE
Thread.currrent[:current_user]

### ISSUE THREAD

**Issue by trev** [rilian/devise-doorkeeper-cancan-api-example#1]
Hey @rilian,

I was looking through your code and saw you use `Thread.current[:current_user]`. Any particular reason?
I even started a SO question about it but figure you'd be the best to shed some light: http://stackoverflow.com/questions/32642652/rails-thread-current-thread-safety

**Comment by rilian** [comment]
hi, i have tested this code using `puma` and `unicorn` and I use similar code in production in some projects under high load and did not experience issues related to thread safety.

you can try yourself, run several puma workers, write a 1-liner that access come critical resource and then load your computer with `ab`

**Comment by rilian** [comment]
@trev please tell me your results so i will close this issue. thanks!

**Comment by trev** [comment]
Thanks @rilian, I wasn't suggesting that there was an issue. I was just wondering why you chose to use `Thread.current[:current_user] = User.find(doorkeeper_token.resource_owner_id)` vs `@current_user = User.find(doorkeeper_token.resource_owner_id)` as both solutions are thread safe.

**Comment by rilian** [comment]
since`Thread.current` is a singleton, it's useful to keep there `current_user` for various purposes. for example to avoid passing `current_user` and `current_ability` down the chain of service objects. 

Maybe my demo code does not have such services that authorise user (using `cancancan`) to do changes, but i often write them in real life projects

**Comment by trev** [comment]
Cool, thanks for taking the time to explain your reasoning. Cheers!

**Comment by rilian** [comment]
thanks!:)

feel free to ask any questions if you need

**Comment by rilian** [comment]
Also, @trev, i use Thread to store current user to be able transparently authenticate user and extend this later. Currently this code gives priority to token-based authentication via Doorkeepr, and you can extend it to any other algorithm. I am not a big fan of Devise and did not want to use the token-based authentication strategy it provides.

Once you write user info inside Thread.currrent[:current_user], any other service can read it independently and use for whatever purposes it is needed. For example, as i mentioned above, checking authorization, logging who did the events happening in the system, etc

as for writing it to `@current_user`, i am not sure it will be accessible in all contexts. But i have not really checked this
